# -*- coding: utf-8 -*-
"""Data_Analytics - Class 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dnrSk6mGCS_VJ_TxaXfwJPpW4-FMR6z-
"""

# Import libraries
import pandas as pd # for table operations - pandas AKA pd
import numpy as np #numerical python - add, sub, mul, avg, mean, mode, median
import matplotlib.pyplot as plt # bar chart, pie chart, Seaborn

# Read the dataset
df = pd.read_csv("/content/banking_transactions.csv") #comma seperated value(not excel)

"""# **Exploratory Data Analysis**
---------------------------
"""

# Display the first 5 rows
df.head()

# Display the last 5 rows
df.tail(10)

# Check the number of rows and columns
df.shape

# Display all column names
df.columns

# Check dataset information and data types
df.info()

# Check the data type of each column
df.dtypes

# Generate summary statistics for numerical columns
df.describe()

# Generate summary statistics for numerical columns
df.describe()

# Generate summary statistics for all columns
df.describe(include="all")

# Check missing values in each column
df.isnull().sum()

# Check missing-value percentages
(df.isnull().sum() / len(df)) * 100

# Check duplicate rows
print(df.duplicated().sum())

# Check duplicate transaction IDs
dti = df["transaction_id"].duplicated().sum()

print(dti)

# Count unique values in each column
df.nunique()

"""# **Data Preprocessing**


### **Step 1: Removing Duplicates**
"""

# Check duplicate rows
duplicate_rows = df.duplicated().sum()

print("Duplicate rows:", duplicate_rows)

# Check duplicate transaction IDs
duplicate_transaction_ids = df["transaction_id"].duplicated().sum()

print("Duplicate transaction IDs:", duplicate_transaction_ids)

"""**Why remove duplicates using transaction_id?**

> A row may not be fully identical because one field could have changed, but if two rows share the same transaction_id, they may still represent the same transaction recorded twice.

```
TX1001 | C101 | 2026-01-10 | 500 | Successful
TX1001 | C101 | 2026-01-10 | 500 | Completed
```


"""

# Display all rows with duplicate transaction IDs
df[df["transaction_id"].duplicated(keep=False)].sort_values("transaction_id")

df = df.drop_duplicates(
    subset="transaction_id",
    keep="first"
)

"""### **Step 2: Check Missing Values**"""

# Check missing values in each column
missing_values = df.isnull().sum()

print(missing_values)

# Show only columns with missing values
missing_values[missing_values > 0]

"""#### **Date**"""

# Display rows where transaction_date is missing
df[df["transaction_date"].isnull()]

"""**Why not fill the date automatically?**

> **[transaction_date]** is a critical field. Using the mean, median, or a random date would create false transaction records. In a real project, these rows would first be checked against the source system.
"""

# Remove rows with missing transaction dates
df = df.dropna(subset=["transaction_date"])

# Verify
print(df["transaction_date"].isnull().sum())

"""#### **transaction amount**"""

print(df["transaction_amount"].isnull().sum())

# Display rows where transaction_amount is missing
df[df["transaction_amount"].isnull()]

"""**`transaction_amount`** is a critical financial field, so filling it with an average could create incorrect transaction values."""

# Remove rows with missing transaction amounts
df = df.dropna(subset=["transaction_amount"])

# Verify
print(df["transaction_amount"].isnull().sum())

"""#### **Handle missing merchant_name**"""

# Display rows where merchant_name is missing
df[df["merchant_name"].isnull()]

# Fill missing merchant names
df["merchant_name"] = df["merchant_name"].fillna("Unknown")

# Verify
print(df["merchant_name"].isnull().sum())

"""#### **Handle missing merchant_category**"""

# Display rows where merchant_category is missing
df[df["merchant_category"].isnull()]

# Fill missing merchant categories
df["merchant_category"] = df["merchant_category"].fillna("Unknown")

# Verify
print(df["merchant_category"].isnull().sum())

"""# Dates"""

# Convert transaction_date to datetime #object to date
df["transaction_date"] = pd.to_datetime(
    df["transaction_date"],
    errors="coerce"
)

# Check the datatype
print(df["transaction_date"].dtype)

print("Invalid or missing dates:", df["transaction_date"].isnull().sum())

# Remove rows with invalid or missing transaction dates
df = df.dropna(subset=["transaction_date"])

# Verify
print("Invalid or missing dates:", df["transaction_date"].isnull().sum())



# Recheck missing values
print("Missing values in each column:")
print(df.isnull().sum()[df.isnull().sum() > 0])

# Recheck complete duplicate rows
print("\nComplete duplicate rows:")
print(df.duplicated().sum())

# Recheck duplicate transaction IDs
print("\nDuplicate transaction IDs:")
print(df["transaction_id"].duplicated().sum())

"""## **Check inconsistent categorical values**"""

# Select categorical columns
categorical_columns = [
    "transaction_type",
    "currency",
    "account_type",
    "merchant_name",
    "merchant_category",
    "payment_method",
    "transaction_channel",
    "transaction_status",
    "location_city"
]

# Display unique values in each categorical column
for column in categorical_columns:
    print(f"\n{column}:")
    print(df[column].unique())

"""**The inconsistencies are mainly in:**

* transaction_type
* currency
* payment_method
* transaction_status

The other categorical columns already look consistent.
"""

# Remove extra spaces from all categorical columns
for column in categorical_columns:
    df[column] = df[column].str.strip()

# Standardize text capitalization #a-A
df["transaction_type"] = df["transaction_type"].str.title()
df["payment_method"] = df["payment_method"].str.title()
df["transaction_status"] = df["transaction_status"].str.title()

# Standardize currency values
df["currency"] = df["currency"].str.upper()

df["currency"] = df["currency"].replace({
    "US DOLLAR": "USD"
})

# verify
print("Transaction types:")
print(df["transaction_type"].unique())

print("\nCurrencies:")
print(df["currency"].unique())

print("\nPayment methods:")
print(df["payment_method"].unique())

print("\nTransaction statuses:")
print(df["transaction_status"].unique())

import matplotlib.pyplot as plt

# Count transactions by type
transaction_counts = df["transaction_type"].value_counts()

# Plot
plt.figure(figsize=(8,5))
transaction_counts.plot(kind="bar")

plt.title("Transaction Count by Transaction Type")
plt.xlabel("Transaction Type")
plt.ylabel("Number of Transactions")
plt.xticks(rotation=45)

plt.show()

import matplotlib.pyplot as plt

# Count transactions by status
status_counts = df["transaction_status"].value_counts()

# Create donut chart
plt.figure(figsize=(6,6))

plt.pie(
    status_counts,
    labels=status_counts.index,
    autopct="%1.1f%%",
    startangle=90
)

# Draw a white circle in the center
centre_circle = plt.Circle((0, 0), 0.70, fc="white")
plt.gca().add_artist(centre_circle)

plt.title("Transaction Status Distribution")

plt.show()

import matplotlib.pyplot as plt

# Sum transaction amount by payment method
payment_amount = df.groupby("payment_method")["transaction_amount"].sum()

# Plot horizontal bar chart
plt.figure(figsize=(8,5))
payment_amount.plot(kind="barh")

plt.title("Total Transaction Amount by Payment Method")
plt.xlabel("Total Transaction Amount")
plt.ylabel("Payment Method")

plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Convert transaction_amount to numeric
df["transaction_amount"] = pd.to_numeric(df["transaction_amount"], errors="coerce")

# Sum transaction amount by payment method
payment_amount = df.groupby("payment_method")["transaction_amount"].sum()

# Plot
plt.figure(figsize=(8,5))
payment_amount.plot(kind="barh")

plt.title("Total Transaction Amount by Payment Method")
plt.xlabel("Total Transaction Amount")
plt.ylabel("Payment Method")

plt.show()

!pip install squarify

import pandas as pd
import matplotlib.pyplot as plt
import squarify

# Convert transaction_amount to numeric (if needed)
df["transaction_amount"] = pd.to_numeric(df["transaction_amount"], errors="coerce")

# Sum transaction amount by merchant category
merchant_data = df.groupby("merchant_category")["transaction_amount"].sum()

# Plot treemap
plt.figure(figsize=(10,6))
squarify.plot(
    sizes=merchant_data.values,
    label=merchant_data.index,
    alpha=0.8
)

plt.title("Transaction Amount by Merchant Category")
plt.axis("off")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Convert transaction_amount to numeric (if needed)
#df["transaction_amount"] = pd.to_numeric(df["transaction_amount"], errors="coerce")

# Sum transaction amount by merchant category
merchant_data = df.groupby("merchant_category")["transaction_amount"].sum()

# Plot bar chart
plt.figure(figsize=(10,5))
merchant_data.plot(kind="bar")

plt.title("Total Transaction Amount by Merchant Category")
plt.xlabel("Merchant Category")
plt.ylabel("Total Transaction Amount")
plt.xticks(rotation=45)

plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Convert transaction_amount to numeric (if needed)
df["transaction_amount"] = pd.to_numeric(df["transaction_amount"], errors="coerce")

# Sum transaction amount by city
city_data = df.groupby("location_city")["transaction_amount"].sum()

# Plot column chart
plt.figure(figsize=(10,5))
city_data.plot(kind="bar")

plt.title("Total Transaction Amount by City")
plt.xlabel("City")
plt.ylabel("Total Transaction Amount")
plt.xticks(rotation=45)

plt.show()

