# -*- coding: utf-8 -*-
"""Data_Analytics - Class 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dnrSk6mGCS_VJ_TxaXfwJPpW4-FMR6z-
"""

# Import libraries
import pandas as pd # for table operations - pandas AKA pd
import numpy as np #numerical python - add, sub, mul, avg, mean, mode, median
import matplotlib.pyplot as plt # bar chart, pie chart, Seaborn

# Read the dataset
df = pd.read_csv("/content/banking_transactions.csv") #comma seperated value(not excel)

"""# **Exploratory Data Analysis**
---------------------------
"""

# Display the first 5 rows
df.head()

# Display the last 5 rows
df.tail(10)

# Check the number of rows and columns
df.shape

# Display all column names
df.columns

# Check dataset information and data types
df.info()

# Check the data type of each column
df.dtypes

# Generate summary statistics for numerical columns
df.describe()

# Generate summary statistics for numerical columns
df.describe()

# Generate summary statistics for all columns
df.describe(include="all")

# Check missing values in each column
df.isnull().sum()

# Check missing-value percentages
(df.isnull().sum() / len(df)) * 100

# Check duplicate rows
print(df.duplicated().sum())

# Check duplicate transaction IDs
dti = df["transaction_id"].duplicated().sum()

print(dti)

# Count unique values in each column
df.nunique()

"""# **Data Preprocessing**


### **Step 1: Removing Duplicates**
"""

# Check duplicate rows
duplicate_rows = df.duplicated().sum()

print("Duplicate rows:", duplicate_rows)

# Check duplicate transaction IDs
duplicate_transaction_ids = df["transaction_id"].duplicated().sum()

print("Duplicate transaction IDs:", duplicate_transaction_ids)

"""**Why remove duplicates using transaction_id?**

> A row may not be fully identical because one field could have changed, but if two rows share the same transaction_id, they may still represent the same transaction recorded twice.

```
TX1001 | C101 | 2026-01-10 | 500 | Successful
TX1001 | C101 | 2026-01-10 | 500 | Completed
```


"""

# Display all rows with duplicate transaction IDs
df[df["transaction_id"].duplicated(keep=False)].sort_values("transaction_id")

df = df.drop_duplicates(
    subset="transaction_id",
    keep="first"
)

"""### **Step 2: Check Missing Values**"""

# Check missing values in each column
missing_values = df.isnull().sum()

print(missing_values)

# Show only columns with missing values
missing_values[missing_values > 0]

"""#### **Date**"""

# Display rows where transaction_date is missing
df[df["transaction_date"].isnull()]

# Remove rows with missing transaction dates
df = df.dropna(subset=["transaction_date"])

# Verify
print(df["transaction_date"].isnull().sum())

"""#### **transaction amount**"""

print(df["transaction_amount"].isnull().sum())

# Display rows where transaction_amount is missing
df[df["transaction_amount"].isnull()]

# Remove rows with missing transaction amounts
df = df.dropna(subset=["transaction_amount"])

# Verify
print(df["transaction_amount"].isnull().sum())

"""#### **Handle missing merchant_name**"""

# Display rows where merchant_name is missing
df[df["merchant_name"].isnull()]

# Fill missing merchant names
df["merchant_name"] = df["merchant_name"].fillna("Unknown")

# Verify
print(df["merchant_name"].isnull().sum())

"""#### **Handle missing merchant_category**"""

# Display rows where merchant_category is missing
df[df["merchant_category"].isnull()]

# Fill missing merchant categories
df["merchant_category"] = df["merchant_category"].fillna("Unknown")

# Verify
print(df["merchant_category"].isnull().sum())

"""# Dates"""

# Convert transaction_date to datetime #object to date
df["transaction_date"] = pd.to_datetime(
    df["transaction_date"],
    errors="coerce"
)

# Check the datatype
print(df["transaction_date"].dtype)

print("Invalid or missing dates:", df["transaction_date"].isnull().sum())

# Remove rows with invalid or missing transaction dates
df = df.dropna(subset=["transaction_date"])

# Verify
print("Invalid or missing dates:", df["transaction_date"].isnull().sum())

# Recheck missing values
print("Missing values in each column:")
print(df.isnull().sum()[df.isnull().sum() > 0])

# Recheck complete duplicate rows
print("\nComplete duplicate rows:")
print(df.duplicated().sum())

# Recheck duplicate transaction IDs
print("\nDuplicate transaction IDs:")
print(df["transaction_id"].duplicated().sum())

"""## **Check inconsistent categorical values**"""

# Select categorical columns
categorical_columns = [
    "transaction_type",
    "currency",
    "account_type",
    "merchant_name",
    "merchant_category",
    "payment_method",
    "transaction_channel",
    "transaction_status",
    "location_city"
]

# Display unique values in each categorical column
for column in categorical_columns:
    print(f"\n{column}:")
    print(df[column].unique())

# Remove extra spaces from all categorical columns
for column in categorical_columns:
    df[column] = df[column].str.strip()

# Standardize text capitalization #a-A
df["transaction_type"] = df["transaction_type"].str.title()
df["payment_method"] = df["payment_method"].str.title()
df["transaction_status"] = df["transaction_status"].str.title()

# Standardize currency values
df["currency"] = df["currency"].str.upper()

df["currency"] = df["currency"].replace({
    "US DOLLAR": "USD"
})

# verify
print("Transaction types:")
print(df["transaction_type"].unique())

print("\nCurrencies:")
print(df["currency"].unique())

print("\nPayment methods:")
print(df["payment_method"].unique())

print("\nTransaction statuses:")
print(df["transaction_status"].unique())

import matplotlib.pyplot as plt

# Count transactions by type
transaction_counts = df["transaction_type"].value_counts()

# Plot
plt.figure(figsize=(8,5))
transaction_counts.plot(kind="bar")

plt.title("Transaction Count by Transaction Type")
plt.xlabel("Transaction Type")
plt.ylabel("Number of Transactions")
plt.xticks(rotation=45)

plt.show()

import matplotlib.pyplot as plt

# Count transaction statuses
status_counts = df["transaction_status"].value_counts()

plt.figure(figsize=(8,8))

wedges, texts, autotexts = plt.pie(
    status_counts,
    labels=None,                 # Hide labels on the chart
    autopct='%1.1f%%',
    startangle=90,
    pctdistance=0.75
)

# Create donut hole
centre_circle = plt.Circle((0, 0), 0.70, fc='white')
plt.gca().add_artist(centre_circle)

# Add legend
plt.legend(
    wedges,
    status_counts.index,
    title="Transaction Status",
    loc="center left",
    bbox_to_anchor=(1, 0.5)
)

plt.title("Transaction Status Distribution")
plt.axis("equal")

plt.savefig("transaction_status_distribution.png", dpi=300, bbox_inches="tight")

from google.colab import files
files.download("transaction_status_distribution.png")

plt.show()

import matplotlib.pyplot as plt

# Count transactions by payment method
payment_counts = df["payment_method"].value_counts()

# Horizontal bar chart
plt.figure(figsize=(8,5))
payment_counts.plot(kind="barh")

plt.title("Customer Payment Method Preferences")
plt.xlabel("Number of Transactions")
plt.ylabel("Payment Method")

plt.savefig("transaction_status_distribution.png", dpi=300, bbox_inches="tight")

from google.colab import files
files.download("transaction_status_distribution.png")

plt.show()

!pip install squarify

import pandas as pd
import matplotlib.pyplot as plt
import squarify

# Convert transaction_amount to numeric (if needed)
df["transaction_amount"] = pd.to_numeric(df["transaction_amount"], errors="coerce")

# Sum transaction amount by merchant category
merchant_data = df.groupby("merchant_category")["transaction_amount"].sum()

# Plot treemap
plt.figure(figsize=(10,6))
squarify.plot(
    sizes=merchant_data.values,
    label=merchant_data.index,
    alpha=0.8
)

plt.title("Transaction Amount by Merchant Category")
plt.axis("off")

plt.savefig("transaction_status_distribution.png", dpi=300, bbox_inches="tight")

from google.colab import files
files.download("transaction_status_distribution.png")

plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Convert transaction_amount to numeric (if needed)
#df["transaction_amount"] = pd.to_numeric(df["transaction_amount"], errors="coerce")

# Sum transaction amount by merchant category
merchant_data = df.groupby("merchant_category")["transaction_amount"].sum()

# Plot bar chart
plt.figure(figsize=(10,5))
merchant_data.plot(kind="bar")

plt.title("Total Transaction Amount by Merchant Category")
plt.xlabel("Merchant Category")
plt.ylabel("Total Transaction Amount")
plt.xticks(rotation=45)

plt.savefig("transaction_status_distribution.png", dpi=300, bbox_inches="tight")

from google.colab import files
files.download("transaction_status_distribution.png")

plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Convert transaction_amount to numeric
df["transaction_amount"] = pd.to_numeric(df["transaction_amount"], errors="coerce")

# Group data
channel_data = df.groupby("transaction_channel").agg(
    Transaction_Count=("transaction_id", "count"),
    Total_Amount=("transaction_amount", "sum")
)

# Bar positions
x = np.arange(len(channel_data))
width = 0.4

# Plot
plt.figure(figsize=(8,5))

plt.bar(x - width/2, channel_data["Transaction_Count"], width, label="Transaction Count")
plt.bar(x + width/2, channel_data["Total_Amount"], width, label="Total Amount")

plt.xticks(x, channel_data.index, rotation=45)
plt.xlabel("Transaction Channel")
plt.ylabel("Value")
plt.title("Transaction Channel Performance")
plt.legend()

plt.savefig("transaction_status_distribution.png", dpi=300, bbox_inches="tight")

from google.colab import files
files.download("transaction_status_distribution.png")

plt.show()

import matplotlib.pyplot as plt

# Count transactions by account type
account_counts = df["account_type"].value_counts()

# Plot column chart
plt.figure(figsize=(8,5))
account_counts.plot(kind="bar")

plt.title("Transaction Activity by Account Type")
plt.xlabel("Account Type")
plt.ylabel("Number of Transactions")
plt.xticks(rotation=45)

plt.savefig("transaction_status_distribution.png", dpi=300, bbox_inches="tight")

from google.colab import files
files.download("transaction_status_distribution.png")

plt.show()

import matplotlib.pyplot as plt

# Top 10 merchants by transaction count
top_merchants = df["merchant_name"].value_counts().head(10)

# Plot horizontal bar chart
plt.figure(figsize=(8,5))
top_merchants.plot(kind="barh")

plt.title("Top 10 Merchants by Transaction Activity")
plt.xlabel("Number of Transactions")
plt.ylabel("Merchant Name")

plt.savefig("transaction_status_distribution.png", dpi=300, bbox_inches="tight")

from google.colab import files
files.download("transaction_status_distribution.png")

plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Convert transaction_date to datetime
df["transaction_date"] = pd.to_datetime(df["transaction_date"])

# Count transactions by date
transaction_trend = df.groupby("transaction_date")["transaction_id"].count()

# Plot line chart
plt.figure(figsize=(10,5))
plt.plot(transaction_trend.index, transaction_trend.values, marker='o')

plt.title("Transaction Activity Over Time")
plt.xlabel("Transaction Date")
plt.ylabel("Number of Transactions")
plt.xticks(rotation=45)

plt.savefig("transaction_status_distribution.png", dpi=300, bbox_inches="tight")

from google.colab import files
files.download("transaction_status_distribution.png")

plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Convert columns to numeric
df["balance_before"] = pd.to_numeric(df["balance_before"], errors="coerce")
df["balance_after"] = pd.to_numeric(df["balance_after"], errors="coerce")

# Scatter plot
plt.figure(figsize=(8,5))

plt.scatter(df["balance_before"], df["balance_after"])

plt.title("Account Balance Before vs After Transactions")
plt.xlabel("Balance Before")
plt.ylabel("Balance After")

plt.savefig("transaction_status_distribution.png", dpi=300, bbox_inches="tight")

from google.colab import files
files.download("transaction_status_distribution.png")

plt.show()
